// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CreateTaskRequest struct {
	Assignees           json.RawMessage `json:"assignees"`
	CustomFields        json.RawMessage `json:"custom_fields"`
	Description         string          `json:"description"`
	MarkdownDescription string          `json:"markdown_description"`
	Name                string          `json:"name"`
	Priority            int             `json:"priority"`
	Status              string          `json:"status"`
	Tags                json.RawMessage `json:"tags"`
}

type CustomField struct {
	Id         string          `json:"id"`
	Name       string          `json:"name"`
	Type       string          `json:"type"`
	TypeConfig json.RawMessage `json:"type_config"`
}

type FieldGetListCustomResponse struct {
	Fields json.RawMessage `json:"fields"`
}

type Folder struct {
	Archived bool   `json:"archived"`
	Hidden   bool   `json:"hidden"`
	Id       string `json:"id"`
	Name     string `json:"name"`
}

type FolderGetResponse struct {
	Folders json.RawMessage `json:"folders"`
}

type List struct {
	Archived  bool            `json:"archived"`
	Id        string          `json:"id"`
	Name      string          `json:"name"`
	Space     json.RawMessage `json:"space"`
	TaskCount int             `json:"task_count"`
}

type ListGetFolderResponse struct {
	Lists json.RawMessage `json:"lists"`
}

type ListGetSpaceResponse struct {
	Lists json.RawMessage `json:"lists"`
}

type Member struct {
	User json.RawMessage `json:"user"`
}

type MemberGetTeamResponse struct {
	Members json.RawMessage `json:"members"`
}

type Space struct {
	Archived bool   `json:"archived"`
	Id       string `json:"id"`
	Name     string `json:"name"`
}

type SpaceGetResponse struct {
	Spaces json.RawMessage `json:"spaces"`
}

type Task struct {
	Assignees    json.RawMessage `json:"assignees"`
	CustomFields json.RawMessage `json:"custom_fields"`
	DateCreated  string          `json:"date_created"`
	Description  string          `json:"description"`
	Id           string          `json:"id"`
	Name         string          `json:"name"`
	Status       json.RawMessage `json:"status"`
	Url          string          `json:"url"`
}

type TaskGetResponse struct {
	Tasks json.RawMessage `json:"tasks"`
}

type Team struct {
	Color   string          `json:"color"`
	Id      string          `json:"id"`
	Members json.RawMessage `json:"members"`
	Name    string          `json:"name"`
}

type TeamGetResponse struct {
	Teams json.RawMessage `json:"teams"`
}
