// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGlossariesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "glossaries",
		Short:  "GraphQL BFF operations for glossaries",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGlossariesCategoriesCmd(flags))
	cmd.AddCommand(newGlossariesCategoriesGroupedValuesCmd(flags))
	cmd.AddCommand(newGlossariesCategoryGroupsCmd(flags))
	cmd.AddCommand(newGlossariesCategoryValuesCmd(flags))
	cmd.AddCommand(newGlossariesCategoryValuesFiltersCmd(flags))
	cmd.AddCommand(newGlossariesProcessingStatusCmd(flags))
	return cmd
}
