// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "organizations",
		Short:  "GraphQL BFF operations for organizations",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrganizationsUsageStatsCmd(flags))
	cmd.AddCommand(newOrganizationsV2Cmd(flags))
	cmd.AddCommand(newOrganizationsWorkspacesCmd(flags))
	return cmd
}
