// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newProductConfigListEnCmd(flags *rootFlags) *cobra.Command {
	var flagCountries string
	var flagUsStates string
	var flagWidgetImmediateLabels string
	var flagWidgetLabels string

	cmd := &cobra.Command{
		Use:         "list-en",
		Short:       "GET /api/product-config/locales/projects.motionapp.com/widget/en/v2",
		Example:     "  motion-pp-cli product-config list-en --countries example-value --us-states example-value --widget-immediate-labels example-value --widget-labels example-value",
		Annotations: map[string]string{"pp:endpoint": "product-config.list_en", "pp:method": "GET", "pp:path": "/api/product-config/locales/projects.motionapp.com/widget/en/v2", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("countries") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "countries")
			}
			if !cmd.Flags().Changed("us-states") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "us-states")
			}
			if !cmd.Flags().Changed("widget-immediate-labels") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "widget-immediate-labels")
			}
			if !cmd.Flags().Changed("widget-labels") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "widget-labels")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/product-config/locales/projects.motionapp.com/widget/en/v2"
			params := map[string]string{}
			if flagCountries != "" {
				params["countries"] = fmt.Sprintf("%v", flagCountries)
			}
			if flagUsStates != "" {
				params["usStates"] = fmt.Sprintf("%v", flagUsStates)
			}
			if flagWidgetImmediateLabels != "" {
				params["widgetImmediateLabels"] = fmt.Sprintf("%v", flagWidgetImmediateLabels)
			}
			if flagWidgetLabels != "" {
				params["widgetLabels"] = fmt.Sprintf("%v", flagWidgetLabels)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "product-config", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCountries, "countries", "", "")
	cmd.Flags().StringVar(&flagUsStates, "us-states", "", "")
	cmd.Flags().StringVar(&flagWidgetImmediateLabels, "widget-immediate-labels", "", "")
	cmd.Flags().StringVar(&flagWidgetLabels, "widget-labels", "", "")

	return cmd
}
