// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBuilderAgentPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagBuilderApiUrl string
	var flagExpiresAt string
	var flagToken string
	var bodyWorkspaceId string

	cmd := &cobra.Command{
		Use:         "builder-agent",
		Short:       "POST /api/builder-agent/token",
		Long:        "Shortcut for 'builder-agent create_token'. POST /api/builder-agent/token",
		Example:     "  motion-pp-cli builder-agent --builder-api-url https://example.com/resource --expires-at 2026-01-15T09:00:00Z --token your-token-here --workspace-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "builder-agent.create_token", "pp:method": "POST", "pp:path": "/api/builder-agent/token"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("builder-api-url") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "builder-api-url")
			}
			if !cmd.Flags().Changed("expires-at") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "expires-at")
			}
			if !cmd.Flags().Changed("token") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "token")
			}
			if !cmd.Flags().Changed("workspace-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "workspace-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/builder-agent/token"
			params := map[string]string{}
			if flagBuilderApiUrl != "" {
				params["builderApiUrl"] = fmt.Sprintf("%v", flagBuilderApiUrl)
			}
			if flagExpiresAt != "" {
				params["expiresAt"] = fmt.Sprintf("%v", flagExpiresAt)
			}
			if flagToken != "" {
				params["token"] = fmt.Sprintf("%v", flagToken)
			}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyWorkspaceId != "" {
				body["workspaceId"] = bodyWorkspaceId
			}
			data, _, err := c.PostWithParams(path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagBuilderApiUrl, "builder-api-url", "", "")
	cmd.Flags().StringVar(&flagExpiresAt, "expires-at", "", "")
	cmd.Flags().StringVar(&flagToken, "token", "", "")
	cmd.Flags().StringVar(&bodyWorkspaceId, "workspace-id", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
