// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newInsightsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDataSourceId string
	var bodyDatePreset string
	var bodyEndDate string
	var bodyFilters string
	var bodyGroupAdsBy string
	var bodyIncludeAdsPerformanceState bool
	var bodyIncludeAggregates bool
	var bodyIncludeGoogleAnalytics bool
	var bodyIncludeGroupAds bool
	var bodyIncludeNorthbeam bool
	var bodyLiveResult bool
	var bodyOffset int
	var bodyPageSize int
	var bodyReportId string
	var bodySortDescending bool
	var bodySortingFieldTypename string
	var bodySortingFieldField string
	var bodySortingFieldIsCustomConversionCost bool
	var bodySortingFieldIsCustomConversionCount bool
	var bodySortingFieldIsCustomConversionPurchase bool
	var bodySortingFieldIsCustomConversionROAS bool
	var bodySortingFieldIsCustomConversionRate bool
	var bodySortingFieldIsCustomConversionValue bool
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:         "insights",
		Short:       "POST /api/v2/insights/getGroupedAdsMetaInsightsV2",
		Long:        "Shortcut for 'insights create_getGroupedAdsMetaInsightsV2'. POST /api/v2/insights/getGroupedAdsMetaInsightsV2",
		Example:     "  motion-pp-cli insights --data-source-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "insights.create_getGroupedAdsMetaInsightsV2", "pp:method": "POST", "pp:path": "/api/v2/insights/getGroupedAdsMetaInsightsV2"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("data-source-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data-source-id")
			}
			if !cmd.Flags().Changed("date-preset") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "date-preset")
			}
			if !cmd.Flags().Changed("end-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "end-date")
			}
			if !cmd.Flags().Changed("filters") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "filters")
			}
			if !cmd.Flags().Changed("group-ads-by") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "group-ads-by")
			}
			if !cmd.Flags().Changed("include-ads-performance-state") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "include-ads-performance-state")
			}
			if !cmd.Flags().Changed("include-aggregates") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "include-aggregates")
			}
			if !cmd.Flags().Changed("include-google-analytics") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "include-google-analytics")
			}
			if !cmd.Flags().Changed("include-group-ads") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "include-group-ads")
			}
			if !cmd.Flags().Changed("include-northbeam") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "include-northbeam")
			}
			if !cmd.Flags().Changed("live-result") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "live-result")
			}
			if !cmd.Flags().Changed("offset") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "offset")
			}
			if !cmd.Flags().Changed("page-size") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "page-size")
			}
			if !cmd.Flags().Changed("report-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "report-id")
			}
			if !cmd.Flags().Changed("sort-descending") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sort-descending")
			}
			if !cmd.Flags().Changed("sorting-field-typename") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-typename")
			}
			if !cmd.Flags().Changed("sorting-field-field") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-field")
			}
			if !cmd.Flags().Changed("sorting-field-is-custom-conversion-cost") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-is-custom-conversion-cost")
			}
			if !cmd.Flags().Changed("sorting-field-is-custom-conversion-count") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-is-custom-conversion-count")
			}
			if !cmd.Flags().Changed("sorting-field-is-custom-conversion-purchase") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-is-custom-conversion-purchase")
			}
			if !cmd.Flags().Changed("sorting-field-is-custom-conversion-roas") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-is-custom-conversion-roas")
			}
			if !cmd.Flags().Changed("sorting-field-is-custom-conversion-rate") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-is-custom-conversion-rate")
			}
			if !cmd.Flags().Changed("sorting-field-is-custom-conversion-value") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "sorting-field-is-custom-conversion-value")
			}
			if !cmd.Flags().Changed("start-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-date")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v2/insights/getGroupedAdsMetaInsightsV2"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDataSourceId != "" {
				body["dataSourceId"] = bodyDataSourceId
			}
			if bodyDatePreset != "" {
				body["datePreset"] = bodyDatePreset
			}
			if bodyEndDate != "" {
				body["endDate"] = bodyEndDate
			}
			if bodyFilters != "" {
				var parsedFilters any
				if err := json.Unmarshal([]byte(bodyFilters), &parsedFilters); err != nil {
					return fmt.Errorf("parsing --filters JSON: %w", err)
				}
				body["filters"] = parsedFilters
			}
			if bodyGroupAdsBy != "" {
				body["groupAdsBy"] = bodyGroupAdsBy
			}
			if cmd.Flags().Changed("include-ads-performance-state") {
				body["includeAdsPerformanceState"] = bodyIncludeAdsPerformanceState
			}
			if cmd.Flags().Changed("include-aggregates") {
				body["includeAggregates"] = bodyIncludeAggregates
			}
			if cmd.Flags().Changed("include-google-analytics") {
				body["includeGoogleAnalytics"] = bodyIncludeGoogleAnalytics
			}
			if cmd.Flags().Changed("include-group-ads") {
				body["includeGroupAds"] = bodyIncludeGroupAds
			}
			if cmd.Flags().Changed("include-northbeam") {
				body["includeNorthbeam"] = bodyIncludeNorthbeam
			}
			if cmd.Flags().Changed("live-result") {
				body["liveResult"] = bodyLiveResult
			}
			if bodyOffset != 0 {
				body["offset"] = bodyOffset
			}
			if bodyPageSize != 0 {
				body["pageSize"] = bodyPageSize
			}
			if bodyReportId != "" {
				body["reportId"] = bodyReportId
			}
			if cmd.Flags().Changed("sort-descending") {
				body["sortDescending"] = bodySortDescending
			}
			{
				nestedSortingField := map[string]any{}
				if bodySortingFieldTypename != "" {
					nestedSortingField["__typename"] = bodySortingFieldTypename
				}
				if bodySortingFieldField != "" {
					nestedSortingField["field"] = bodySortingFieldField
				}
				if cmd.Flags().Changed("sorting-field-is-custom-conversion-cost") {
					nestedSortingField["isCustomConversionCost"] = bodySortingFieldIsCustomConversionCost
				}
				if cmd.Flags().Changed("sorting-field-is-custom-conversion-count") {
					nestedSortingField["isCustomConversionCount"] = bodySortingFieldIsCustomConversionCount
				}
				if cmd.Flags().Changed("sorting-field-is-custom-conversion-purchase") {
					nestedSortingField["isCustomConversionPurchase"] = bodySortingFieldIsCustomConversionPurchase
				}
				if cmd.Flags().Changed("sorting-field-is-custom-conversion-roas") {
					nestedSortingField["isCustomConversionROAS"] = bodySortingFieldIsCustomConversionROAS
				}
				if cmd.Flags().Changed("sorting-field-is-custom-conversion-rate") {
					nestedSortingField["isCustomConversionRate"] = bodySortingFieldIsCustomConversionRate
				}
				if cmd.Flags().Changed("sorting-field-is-custom-conversion-value") {
					nestedSortingField["isCustomConversionValue"] = bodySortingFieldIsCustomConversionValue
				}
				if len(nestedSortingField) > 0 {
					body["sortingField"] = nestedSortingField
				}
			}
			if bodyStartDate != "" {
				body["startDate"] = bodyStartDate
			}
			data, _, err := c.PostWithParams(path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDataSourceId, "data-source-id", "", "")
	cmd.Flags().StringVar(&bodyDatePreset, "date-preset", "", "")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "")
	cmd.Flags().StringVar(&bodyFilters, "filters", "", "")
	cmd.Flags().StringVar(&bodyGroupAdsBy, "group-ads-by", "", "")
	cmd.Flags().BoolVar(&bodyIncludeAdsPerformanceState, "include-ads-performance-state", false, "")
	cmd.Flags().BoolVar(&bodyIncludeAggregates, "include-aggregates", false, "")
	cmd.Flags().BoolVar(&bodyIncludeGoogleAnalytics, "include-google-analytics", false, "")
	cmd.Flags().BoolVar(&bodyIncludeGroupAds, "include-group-ads", false, "")
	cmd.Flags().BoolVar(&bodyIncludeNorthbeam, "include-northbeam", false, "")
	cmd.Flags().BoolVar(&bodyLiveResult, "live-result", false, "")
	cmd.Flags().IntVar(&bodyOffset, "offset", 0, "")
	cmd.Flags().IntVar(&bodyPageSize, "page-size", 0, "")
	cmd.Flags().StringVar(&bodyReportId, "report-id", "", "")
	cmd.Flags().BoolVar(&bodySortDescending, "sort-descending", false, "")
	cmd.Flags().StringVar(&bodySortingFieldTypename, "sorting-field-typename", "", "")
	cmd.Flags().StringVar(&bodySortingFieldField, "sorting-field-field", "", "")
	cmd.Flags().BoolVar(&bodySortingFieldIsCustomConversionCost, "sorting-field-is-custom-conversion-cost", false, "")
	cmd.Flags().BoolVar(&bodySortingFieldIsCustomConversionCount, "sorting-field-is-custom-conversion-count", false, "")
	cmd.Flags().BoolVar(&bodySortingFieldIsCustomConversionPurchase, "sorting-field-is-custom-conversion-purchase", false, "")
	cmd.Flags().BoolVar(&bodySortingFieldIsCustomConversionROAS, "sorting-field-is-custom-conversion-roas", false, "")
	cmd.Flags().BoolVar(&bodySortingFieldIsCustomConversionRate, "sorting-field-is-custom-conversion-rate", false, "")
	cmd.Flags().BoolVar(&bodySortingFieldIsCustomConversionValue, "sorting-field-is-custom-conversion-value", false, "")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
