// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWorkspacesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "workspaces",
		Short:  "GraphQL BFF operations for workspaces",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWorkspacesAccessRequestsCmd(flags))
	cmd.AddCommand(newWorkspacesCategoriesCmd(flags))
	cmd.AddCommand(newWorkspacesFoldersAndReportsCmd(flags))
	cmd.AddCommand(newWorkspacesSharedTargetsCmd(flags))
	cmd.AddCommand(newWorkspacesTrendingVisualFormatsCmd(flags))
	return cmd
}
