// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFolderListCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Manage list",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFolderListGetFolderCmd(flags))
	return cmd
}
