// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSpaceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "space",
		Short:  "Manage space",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSpaceFolderCmd(flags))
	cmd.AddCommand(newSpaceListCmd(flags))
	return cmd
}
