// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTaskCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "task",
		Short:  "Manage task",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTaskGetCmd(flags))
	cmd.AddCommand(newTaskUpdateCmd(flags))
	cmd.AddCommand(newTaskFieldCmd(flags))
	return cmd
}
