// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTeamSpaceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "space",
		Short: "Manage space",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTeamSpaceGetCmd(flags))
	return cmd
}
