// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "gid", "sid", "uid", "uuid", "guid", "name", "slug", "key", "code"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

// TestUpsertBatch_PopulatesFolderListTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed folder_list table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesFolderListTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "folder_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "folder_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "folder_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("folder_list", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "folder_list").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "folder_list")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count folder_list: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("folder_list count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandFolderListGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandFolderListGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "folder_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("folder_list", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "folder_list").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "folder_list")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count folder_list: %v", err)
	}
	if typed != 0 {
		t.Fatalf("folder_list count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "folder_id")
	}
}

// TestUpsertBatch_PopulatesListTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed list table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesListTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("list", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "list").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "list")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count list: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("list count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesListFieldTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed list_field table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesListFieldTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "list_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "list_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "list_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("list_field", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "list_field").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "list_field")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count list_field: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("list_field count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandListFieldGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandListFieldGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "list_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("list_field", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "list_field").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "list_field")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count list_field: %v", err)
	}
	if typed != 0 {
		t.Fatalf("list_field count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "list_id")
	}
}

// TestUpsertBatch_PopulatesListTaskTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed list_task table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesListTaskTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "list_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "list_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "list_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("list_task", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "list_task").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "list_task")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count list_task: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("list_task count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandListTaskGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandListTaskGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "list_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("list_task", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "list_task").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "list_task")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count list_task: %v", err)
	}
	if typed != 0 {
		t.Fatalf("list_task count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "list_id")
	}
}

// TestUpsertBatch_PopulatesSpaceFolderTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed space_folder table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSpaceFolderTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "space_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "space_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "space_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("space_folder", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "space_folder").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "space_folder")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count space_folder: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("space_folder count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandSpaceFolderGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandSpaceFolderGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "space_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("space_folder", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "space_folder").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "space_folder")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count space_folder: %v", err)
	}
	if typed != 0 {
		t.Fatalf("space_folder count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "space_id")
	}
}

// TestUpsertBatch_PopulatesSpaceListTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed space_list table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSpaceListTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "space_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "space_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "space_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("space_list", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "space_list").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "space_list")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count space_list: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("space_list count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandSpaceListGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandSpaceListGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "space_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("space_list", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "space_list").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "space_list")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count space_list: %v", err)
	}
	if typed != 0 {
		t.Fatalf("space_list count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "space_id")
	}
}

// TestUpsertBatch_PopulatesTaskTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed task table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTaskTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("task", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "task").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "task")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count task: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("task count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTaskFieldTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed task_field table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTaskFieldTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "task_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "task_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "task_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("task_field", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "task_field").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "task_field")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count task_field: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("task_field count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandTaskFieldGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandTaskFieldGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "task_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("task_field", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "task_field").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "task_field")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count task_field: %v", err)
	}
	if typed != 0 {
		t.Fatalf("task_field count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "task_id")
	}
}

// TestUpsertBatch_PopulatesMemberTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed member table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesMemberTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "team_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "team_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "team_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("member", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "member").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "member")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count member: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("member count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandMemberGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandMemberGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "team_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("member", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "member").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "member")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count member: %v", err)
	}
	if typed != 0 {
		t.Fatalf("member count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "team_id")
	}
}

// TestUpsertBatch_PopulatesTeamSpaceTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed team_space table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTeamSpaceTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "team_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "team_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "team_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("team_space", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "team_space").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "team_space")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count team_space: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("team_space count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandTeamSpaceGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandTeamSpaceGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "team_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("team_space", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "team_space").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "team_space")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count team_space: %v", err)
	}
	if typed != 0 {
		t.Fatalf("team_space count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "team_id")
	}
}
