// Copyright 2026 theprodigal95. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"motion-pp-cli/internal/cli"
	"motion-pp-cli/internal/client"
	"motion-pp-cli/internal/config"
	"motion-pp-cli/internal/mcp/cobratree"
	"motion-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("ais_agent_workflow_runs",
			mcplib.WithDescription("Fetch ais agent workflow runs. Required: operationName (default: aiAgentWorkflowRuns). Optional: query, variables. Returns the new ai_agent_workflow_runs."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("availables_workspace_tags",
			mcplib.WithDescription("Fetch availables workspace tags. Required: operationName (default: GetAvailableWorkspaceTags). Optional: query, variables. Returns the new get_available_workspace_tags."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("bootstraps_get",
			mcplib.WithDescription("Fetch bootstraps. Required: operationName (default: Bootstrap). Optional: query, variables. Returns the new bootstrap."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("brands_in_workspace",
			mcplib.WithDescription("Fetch brands in workspace. Required: operationName (default: BrandInWorkspace). Optional: query, variables. Returns the new brand_in_workspace."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("builder-agent_create_token",
			mcplib.WithDescription("POST /api/builder-agent/token. Required: builderApiUrl, expiresAt, token, workspaceId. Returns the new token."),
			mcplib.WithString("builderApiUrl", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("expiresAt", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("token", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("workspaceId", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/builder-agent/token", false, []mcpParamBinding{{PublicName: "builderApiUrl", WireName: "builderApiUrl", Location: "query"}, {PublicName: "expiresAt", WireName: "expiresAt", Location: "query"}, {PublicName: "token", WireName: "token", Location: "query"}, {PublicName: "workspaceId", WireName: "workspaceId", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("creative_list_get_ad_comments_by_creative_asset_web",
			mcplib.WithDescription("GET /api/v2/creative/getAdCommentsByCreativeAssetWeb. Optional: creativeAssetId. Returns the getAdCommentsByCreativeAssetWeb."),
			mcplib.WithString("creativeAssetId", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/v2/creative/getAdCommentsByCreativeAssetWeb", false, []mcpParamBinding{{PublicName: "creativeAssetId", WireName: "creativeAssetId", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("creatives_assets",
			mcplib.WithDescription("Fetch creatives assets. Required: operationName (default: GetCreativeAssets). Optional: query, variables. Returns the new get_creative_assets."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("creatives_highlights",
			mcplib.WithDescription("Fetch creatives highlights. Required: operationName (default: CreativeHighlights). Optional: query, variables. Returns the new creative_highlights."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("customs_conversions",
			mcplib.WithDescription("Fetch customs conversions. Required: operationName (default: CustomConversions). Optional: query, variables. Returns the new custom_conversions."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("datas_source_v2",
			mcplib.WithDescription("Fetch datas source v2. Required: operationName (default: DataSourceV2). Optional: query, variables. Returns the new data_source_v2."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("datas_sources",
			mcplib.WithDescription("Fetch datas sources. Required: operationName (default: DataSources). Optional: query, variables. Returns the new data_sources."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("defaults_brands",
			mcplib.WithDescription("Fetch defaults brands. Required: operationName (default: DefaultBrands). Optional: query, variables (default: map[]). Returns the new default_brands."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("displays_metrics_presets",
			mcplib.WithDescription("Fetch displays metrics presets. Required: operationName (default: DisplayMetricsPresets). Optional: query, variables (default: map[]). Returns the new display_metrics_presets."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("facebooks_user",
			mcplib.WithDescription("Fetch facebooks user. Required: operationName (default: FacebookUser). Optional: query, variables. Returns the new facebook_user."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("glossaries_categories",
			mcplib.WithDescription("Fetch glossaries categories. Required: operationName (default: GlossaryCategories). Optional: query, variables. Returns the new glossary_categories."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("glossaries_categories_grouped_values",
			mcplib.WithDescription("Fetch glossaries categories grouped values. Required: operationName. Optional: query, variables. Returns the new glossary_categories_grouped_values."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("glossaries_category_groups",
			mcplib.WithDescription("Fetch glossaries category groups. Required: operationName (default: GlossaryCategoryGroups). Optional: query, variables (default: map[]). Returns the new glossary_category_groups."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("glossaries_category_values",
			mcplib.WithDescription("Fetch glossaries category values. Required: operationName (default: GlossaryCategoryValues). Optional: query, variables. Returns the new glossary_category_values."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("glossaries_category_values_filters",
			mcplib.WithDescription("Fetch glossaries category values filters. Required: operationName (default: GlossaryCategoryValuesFilters). Optional: query, variables. Returns the new glossary_category_values_filters."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("glossaries_processing_status",
			mcplib.WithDescription("Fetch glossaries processing status. Required: operationName (default: GlossaryProcessingStatus). Optional: query, variables. Returns the new glossary_processing_status."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("has_messaging_angle_data",
			mcplib.WithDescription("Fetch has messaging angle data. Required: operationName (default: HasMessagingAngleData). Optional: query, variables. Returns the new has_messaging_angle_data."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("has_visual_format_data",
			mcplib.WithDescription("Fetch has visual format data. Required: operationName (default: HasVisualFormatData). Optional: query, variables. Returns the new has_visual_format_data."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("insights_create_get_grouped_ads_meta_insights_v2",
			mcplib.WithDescription("POST /api/v2/insights/getGroupedAdsMetaInsightsV2. Required: dataSourceId, datePreset, endDate, filters, groupAdsBy, includeAdsPerformanceState, includeAggregates, includeGoogleAnalytics, includeGroupAds, includeNorthbeam, liveResult, offset, pageSize, reportId, sortDescending, sortingField, startDate. Returns the new getGroupedAdsMetaInsightsV2."),
			mcplib.WithString("dataSourceId", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("datePreset", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("endDate", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("filters", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("groupAdsBy", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("includeAdsPerformanceState", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("includeAggregates", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("includeGoogleAnalytics", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("includeGroupAds", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("includeNorthbeam", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("liveResult", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("offset", mcplib.Required(), mcplib.Description("")),
			mcplib.WithNumber("pageSize", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("reportId", mcplib.Required(), mcplib.Description("")),
			mcplib.WithBoolean("sortDescending", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("sortingField", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("startDate", mcplib.Required(), mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/v2/insights/getGroupedAdsMetaInsightsV2", false, []mcpParamBinding{{PublicName: "dataSourceId", WireName: "dataSourceId", Location: "body"}, {PublicName: "datePreset", WireName: "datePreset", Location: "body"}, {PublicName: "endDate", WireName: "endDate", Location: "body"}, {PublicName: "filters", WireName: "filters", Location: "body"}, {PublicName: "groupAdsBy", WireName: "groupAdsBy", Location: "body"}, {PublicName: "includeAdsPerformanceState", WireName: "includeAdsPerformanceState", Location: "body"}, {PublicName: "includeAggregates", WireName: "includeAggregates", Location: "body"}, {PublicName: "includeGoogleAnalytics", WireName: "includeGoogleAnalytics", Location: "body"}, {PublicName: "includeGroupAds", WireName: "includeGroupAds", Location: "body"}, {PublicName: "includeNorthbeam", WireName: "includeNorthbeam", Location: "body"}, {PublicName: "liveResult", WireName: "liveResult", Location: "body"}, {PublicName: "offset", WireName: "offset", Location: "body"}, {PublicName: "pageSize", WireName: "pageSize", Location: "body"}, {PublicName: "reportId", WireName: "reportId", Location: "body"}, {PublicName: "sortDescending", WireName: "sortDescending", Location: "body"}, {PublicName: "sortingField", WireName: "sortingField", Location: "body"}, {PublicName: "startDate", WireName: "startDate", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("is_report_shared",
			mcplib.WithDescription("Fetch is report shared. Required: operationName (default: IsReportShared). Optional: query, variables. Returns the new is_report_shared."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("messagings_angle_analysis",
			mcplib.WithDescription("Fetch messagings angle analysis. Required: operationName (default: GetMessagingAngleAnalysis). Optional: query, variables. Returns the new get_messaging_angle_analysis."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("organization_list_697a256b66437695f674687d",
			mcplib.WithDescription("Fetch structured links from /organization/6214fe5e1ccc60d23897d87b/697a256b66437695f674687d. Returns the html."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/organization/6214fe5e1ccc60d23897d87b/697a256b66437695f674687d", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("organizations_usage_stats",
			mcplib.WithDescription("Fetch organizations usage stats. Required: operationName (default: OrganizationUsageStats). Optional: query, variables. Returns the new organization_usage_stats."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("organizations_v2",
			mcplib.WithDescription("Fetch organizations v2. Required: operationName (default: OrganizationV2). Optional: query, variables. Returns the new organization_v2."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("organizations_workspaces",
			mcplib.WithDescription("Fetch organizations workspaces. Required: operationName (default: QueryOrganizationWorkspaces). Optional: query, variables. Returns the new query_organization_workspaces."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("product-config_list_en",
			mcplib.WithDescription("GET /api/product-config/locales/projects.motionapp.com/widget/en/v2. Required: countries, usStates, widgetImmediateLabels, widgetLabels. Returns the en."),
			mcplib.WithString("countries", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("usStates", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("widgetImmediateLabels", mcplib.Required(), mcplib.Description("")),
			mcplib.WithString("widgetLabels", mcplib.Required(), mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/product-config/locales/projects.motionapp.com/widget/en/v2", false, []mcpParamBinding{{PublicName: "countries", WireName: "countries", Location: "query"}, {PublicName: "usStates", WireName: "usStates", Location: "query"}, {PublicName: "widgetImmediateLabels", WireName: "widgetImmediateLabels", Location: "query"}, {PublicName: "widgetLabels", WireName: "widgetLabels", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("product-config_options_en",
			mcplib.WithDescription("OPTIONS /api/product-config/locales/projects.motionapp.com/widget/en/v2. Returns the en."),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("OPTIONS", "/api/product-config/locales/projects.motionapp.com/widget/en/v2", false, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("shareds_reports",
			mcplib.WithDescription("Fetch shareds reports. Required: operationName (default: SharedReports). Optional: query, variables. Returns the new shared_reports."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("signal_options_sse",
			mcplib.WithDescription("OPTIONS /api/signal/products/projects.motionapp.com/notifications/sse/{uuid}/. Required: uuid. Returns the sse."),
			mcplib.WithString("uuid", mcplib.Required(), mcplib.Description("The uuid path segment")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("OPTIONS", "/api/signal/products/projects.motionapp.com/notifications/sse/{uuid}/", false, []mcpParamBinding{{PublicName: "uuid", WireName: "uuid", Location: "path"}}, []string{"uuid"}),
	)
	s.AddTool(
		mcplib.NewTool("slacks_connection",
			mcplib.WithDescription("Fetch slacks connection. Required: operationName (default: GetSlackConnection). Optional: query, variables. Returns the new get_slack_connection."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tops_ads_report",
			mcplib.WithDescription("Fetch tops ads report. Required: operationName (default: TopAdsReport). Optional: query, variables. Returns the new top_ads_report."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("tops_saved_creatives",
			mcplib.WithDescription("Fetch tops saved creatives. Required: operationName (default: TopSavedCreatives). Optional: query, variables (default: map[filters:<nil> limit:16]). Returns the new top_saved_creatives."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("trials_checklist_competitor_logos",
			mcplib.WithDescription("Fetch trials checklist competitor logos. Required: operationName (default: TrialChecklistCompetitorLogos). Optional: query, variables. Returns the new trial_checklist_competitor_logos."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("verifies_data_source_fb_access",
			mcplib.WithDescription("Fetch verifies data source fb access. Required: operationName (default: VerifyDataSourceFbAccess). Optional: query, variables. Returns the new verify_data_source_fb_access."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_access_requests",
			mcplib.WithDescription("Fetch workspaces access requests. Required: operationName (default: WorkspaceAccessRequests). Optional: query, variables. Returns the new workspace_access_requests."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_categories",
			mcplib.WithDescription("Fetch workspaces categories. Required: operationName (default: WorkspaceCategories). Optional: query, variables. Returns the new workspace_categories."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_folders_and_reports",
			mcplib.WithDescription("Fetch workspaces folders and reports. Required: operationName (default: WorkspaceFoldersAndReports). Optional: query, variables. Returns the new workspace_folders_and_reports."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_shared_targets",
			mcplib.WithDescription("Fetch workspaces shared targets. Required: operationName (default: WorkspaceSharedTargets). Optional: query, variables. Returns the new workspace_shared_targets."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_trending_visual_formats",
			mcplib.WithDescription("Fetch workspaces trending visual formats. Required: operationName (default: WorkspaceTrendingVisualFormats). Optional: query, variables. Returns the new workspace_trending_visual_formats."),
			mcplib.WithString("operationName", mcplib.Required(), mcplib.Description("GraphQL operation name")),
			mcplib.WithString("query", mcplib.Description("GraphQL query document")),
			mcplib.WithString("variables", mcplib.Description("GraphQL variables as JSON")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/graphql", false, []mcpParamBinding{{PublicName: "operationName", WireName: "operationName", Location: "body"}, {PublicName: "query", WireName: "query", Location: "body"}, {PublicName: "variables", WireName: "variables", Location: "body"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      See API docs: https://projects.motionapp.com" +
					"\n      Run 'motion-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      See API docs: https://projects.motionapp.com" +
					"\n      Run 'motion-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "motion-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 2)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "motion-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "motion",
		"description": "Discovered API spec for projects-motionapp",
		"archetype":   "developer-platform",
		"tool_count":  43,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion motion-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "ais",
				"description": "GraphQL BFF operations for ais",
				"endpoints":   []string{"agent_workflow_runs"},
				"searchable":  true,
			},
			{
				"name":        "availables",
				"description": "GraphQL BFF operations for availables",
				"endpoints":   []string{"workspace_tags"},
				"searchable":  true,
			},
			{
				"name":        "bootstraps",
				"description": "GraphQL BFF operations for bootstraps",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "brands",
				"description": "GraphQL BFF operations for brands",
				"endpoints":   []string{"in_workspace"},
				"searchable":  true,
			},
			{
				"name":        "builder-agent",
				"description": "Operations on token",
				"endpoints":   []string{"create_token"},
				"searchable":  true,
			},
			{
				"name":        "creative",
				"description": "Operations on getAdCommentsByCreativeAssetWeb",
				"endpoints":   []string{"list_getAdCommentsByCreativeAssetWeb"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "creatives",
				"description": "GraphQL BFF operations for creatives",
				"endpoints":   []string{"assets", "highlights"},
				"searchable":  true,
			},
			{
				"name":        "customs",
				"description": "GraphQL BFF operations for customs",
				"endpoints":   []string{"conversions"},
				"searchable":  true,
			},
			{
				"name":        "datas",
				"description": "GraphQL BFF operations for datas",
				"endpoints":   []string{"source_v2", "sources"},
				"searchable":  true,
			},
			{
				"name":        "defaults",
				"description": "GraphQL BFF operations for defaults",
				"endpoints":   []string{"brands"},
				"searchable":  true,
			},
			{
				"name":        "displays",
				"description": "GraphQL BFF operations for displays",
				"endpoints":   []string{"metrics_presets"},
				"searchable":  true,
			},
			{
				"name":        "facebooks",
				"description": "GraphQL BFF operations for facebooks",
				"endpoints":   []string{"user"},
				"searchable":  true,
			},
			{
				"name":        "glossaries",
				"description": "GraphQL BFF operations for glossaries",
				"endpoints":   []string{"categories", "categories_grouped_values", "category_groups", "category_values", "category_values_filters", "processing_status"},
				"searchable":  true,
			},
			{
				"name":        "has",
				"description": "GraphQL BFF operations for has",
				"endpoints":   []string{"messaging_angle_data", "visual_format_data"},
				"searchable":  true,
			},
			{
				"name":        "insights",
				"description": "Operations on getGroupedAdsMetaInsightsV2",
				"endpoints":   []string{"create_getGroupedAdsMetaInsightsV2"},
				"searchable":  true,
			},
			{
				"name":        "is",
				"description": "GraphQL BFF operations for is",
				"endpoints":   []string{"report_shared"},
				"searchable":  true,
			},
			{
				"name":        "messagings",
				"description": "GraphQL BFF operations for messagings",
				"endpoints":   []string{"angle_analysis"},
				"searchable":  true,
			},
			{
				"name":        "organization",
				"description": "Operations on 697a256b66437695f674687d",
				"endpoints":   []string{"list_697a256b66437695f674687d"},
				"syncable":    true,
			},
			{
				"name":        "organizations",
				"description": "GraphQL BFF operations for organizations",
				"endpoints":   []string{"usage_stats", "v2", "workspaces"},
				"searchable":  true,
			},
			{
				"name":        "product-config",
				"description": "Operations on en",
				"endpoints":   []string{"list_en", "options_en"},
				"searchable":  true,
			},
			{
				"name":        "shareds",
				"description": "GraphQL BFF operations for shareds",
				"endpoints":   []string{"reports"},
				"searchable":  true,
			},
			{
				"name":        "signal",
				"description": "Operations on sse",
				"endpoints":   []string{"options_sse"},
			},
			{
				"name":        "slacks",
				"description": "GraphQL BFF operations for slacks",
				"endpoints":   []string{"connection"},
				"searchable":  true,
			},
			{
				"name":        "tops",
				"description": "GraphQL BFF operations for tops",
				"endpoints":   []string{"ads_report", "saved_creatives"},
				"searchable":  true,
			},
			{
				"name":        "trials",
				"description": "GraphQL BFF operations for trials",
				"endpoints":   []string{"checklist_competitor_logos"},
				"searchable":  true,
			},
			{
				"name":        "verifies",
				"description": "GraphQL BFF operations for verifies",
				"endpoints":   []string{"data_source_fb_access"},
				"searchable":  true,
			},
			{
				"name":        "workspaces",
				"description": "GraphQL BFF operations for workspaces",
				"endpoints":   []string{"access_requests", "categories", "folders_and_reports", "shared_targets", "trending_visual_formats"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Resource discovery", "insight": "Use list commands to discover available resources before attempting operations. Developer platform APIs often have nested resource hierarchies."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
